services:
    java-backend:
        image: emberflexberry-java/backend
        build: Java/src/main/webapp
        environment:
            DB_ADDR: app-postgres-db
            DB_NAME: appdb
            DB_USER: flexberryuser
            DB_PASS: jhv
        ports:
            - "8080:8080"
 
    app-postgres-db:
        image: emberflexberry-java/postgre-sql
        volumes:
            - DB:/var/lib/pgsql/data/
        ports:
            - "5432:5432"
volumes:
  DB:
