name: build and run tests

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2.3.1
      with:
       persist-credentials: false
          
    - name: Build images backend and database
      run: |
       set -x
       node -v
       sh create-image-backend.sh
       sh create-image-database.sh
       
    - name: clone flexberry data
      run: |
       git clone https://github.com/Flexberry/ember-flexberry-data.git ember-flexberry-data
       
    - name: build frontend image
      run: |
       sh create-image-frontend.sh
       
    - name: run compose
      run: |
       docker-compose up -d
       
    - name: Run Google Chrome
      run: |
        sudo chown root /opt/google/chrome/chrome-sandbox
        sudo sudo chmod 4755 /opt/google/chrome/chrome-sandbox
        google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost/tests &

    - name: Shutdown docker services
      run: |
        docker-compose down

