name: build and run tests

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2.3.1
      with:
       persist-credentials: false

    - name: Build images and run
      run: |
       set -x
       node -v
       sh create-image-backend.sh
       sh create-image-database.sh
       docker-compose up -d

    - name: clone flexberry data
      run: |
       git clone -b feature-ember-update https://github.com/Flexberry/ember-flexberry-data.git ember-flexberry-data

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Init NodeJS env
      run: |
       set -x
       node -v
       npm install -g bower
       npm install -g ember-cli@3.1.4
       cd ember-flexberry-data
       npm install
       bower install

    - name: Run Google Chrome
      run: |
        sudo chown root /opt/google/chrome/chrome-sandbox
        sudo sudo chmod 4755 /opt/google/chrome/chrome-sandbox
        google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &

    - name: Run addon tests
      if: ${{ success() || steps.linting.conclusion == 'failure' }}
      run: |
        set -x
        cd ember-flexberry-data
        ember try:one ember-default --skip-cleanup

    - name: Shutdown docker services
      run: |
        docker-compose down
